package be.lmenten.avr.core.utils;

public enum CoreIORegisters
{
	PINA, DDRA, PORTA,
	PINB, DDRB, PORTB,
	PINC, DDRC, PORTC,
	PIND, DDRD, PORTD,
	PINE, DDRE, PORTE,
	PINF, DDRF, PORTF,
	PING, DDRG, PORTG,

	TIFR0, TIFR1, TIFR2, TIFR3, TIFR4, TIFR5, PCIFR,

	EIFR, EIMSK,

	GPIOR0,

	EECR, EEDR, EEARL, EEARH, 

	GTCCR,
	TCCR0A, TCCR0B,
	TCNT0,
	OCR0A, OCR0B,
	GPIOR1, GPIOR2,

	SPCR,
	SPSR,
	SPDR,

	ACSR,

	OCDR,

	SMCR,
	MCUSR, MCUCR,
	SPMCSR,

	RAMPD,
	RAMPX, RAMPY, RAMPZ,
	EIND,
	SPL, SPH,
	SREG,

	WDTSCR,
	CLKPR,
	PRR0, PRR1,
	OSCCAL,
	PCICR,
	EICRA, EICRB,
	PCMSK0, PCMSK1, PCMSK2,
	TIMSK0, TIMSK1, TIMSK2, TIMSK3, TIMSK4, TIMSK5,
	XMCRA, XMCRB,
	ADCL, ADCH,
	ADCSRA, ADCSRB,
	ADMUX,
	DIDR0, DIDR1, DIDR2,

	TCCR1A, TCCR1B, TCCR1C,
	TCNT1L, TCNT1H,
	ICR1L, ICR1H,
	OCR1AL, OCR1AH, OCR1BL, OCR1BH, OCR1CL, OCR1CH,

	TCCR3A, TCCR3B, TCCR3C,
	TCNT3L, TCNT3H,
	ICR3L, ICR3H,
	OCR3AL, OCR3AH, OCR3BL, OCR3BH, OCR3CL, OCR3CH,

	TCCR4A, TCCR4B, TCCR4C,
	TCNT4L, TCNT4H,
	ICR4L, ICR4H,
	OCR4AL, OCR4AH, OCR4BL, OCR4BH, OCR4CL, OCR4CH,

	TCCR2A, TCCR2B,
	TCNT2,
	OCR2A, OCR2B,

	ASSR,

	TWBR, TWSR, TWAR, TWDR, TWCR, TWAMR,

	UCSR0A, UCSR0B, UCSR0C,
	UBRR0L, UBRR0H,
	UDR0,
	
	UCSR1A, UCSR1B, UCSR1C,
	UBRR1L, UBRR1H,
	UDR1,
	
	UCSR2A, UCSR2B, UCSR2C,
	UBRR2L, UBRR2H,
	UDR2,
	
	PINH, DDRH, PORTH,
	PINJ, DDRJ, PORTJ,
	PINK, DDRK, PORTK,
	PINL, DDRL, PORTL,

	TCCR5A, TCCR5B, TCCR5C,
	TCNT5L, TCNT5H,
	ICR5L, ICR5H,
	OCR5AL, OCR5AH, OCR5BL, OCR5BH, OCR5CL, OCR5CH,

	UCSR3A, UCSR3B, UCSR3C,
	UBRR3L, UBRR3H,
	UDR3,
	;
}
