/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.node;

import be.lmenten.avr.assembler.parser.analysis.*;

@SuppressWarnings("nls")
public final class ACodeLine extends PLine
{
    private PInstruction _instruction_;

    public ACodeLine()
    {
        // Constructor
    }

    public ACodeLine(
        @SuppressWarnings("hiding") PInstruction _instruction_)
    {
        // Constructor
        setInstruction(_instruction_);

    }

    @Override
    public Object clone()
    {
        return new ACodeLine(
            cloneNode(this._instruction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACodeLine(this);
    }

    public PInstruction getInstruction()
    {
        return this._instruction_;
    }

    public void setInstruction(PInstruction node)
    {
        if(this._instruction_ != null)
        {
            this._instruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instruction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instruction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instruction_ == child)
        {
            this._instruction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instruction_ == oldChild)
        {
            setInstruction((PInstruction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
