/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.node;

import java.util.*;

import be.lmenten.avr.assembler.parser.analysis.*;

@SuppressWarnings("nls")
public final class ADbLine extends PLine
{
    private final LinkedList<PExpr> _data_ = new LinkedList<PExpr>();

    public ADbLine()
    {
        // Constructor
    }

    public ADbLine(
        @SuppressWarnings("hiding") List<?> _data_)
    {
        // Constructor
        setData(_data_);

    }

    @Override
    public Object clone()
    {
        return new ADbLine(
            cloneList(this._data_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADbLine(this);
    }

    public LinkedList<PExpr> getData()
    {
        return this._data_;
    }

    public void setData(List<?> list)
    {
        for(PExpr e : this._data_)
        {
            e.parent(null);
        }
        this._data_.clear();

        for(Object obj_e : list)
        {
            PExpr e = (PExpr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._data_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._data_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._data_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpr> i = this._data_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
