/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.node;

import be.lmenten.avr.assembler.parser.analysis.*;

@SuppressWarnings("nls")
public final class AIndexExpr extends PExpr
{
    private TIdentifier _register_;
    private TIdentifier _bit_;

    public AIndexExpr()
    {
        // Constructor
    }

    public AIndexExpr(
        @SuppressWarnings("hiding") TIdentifier _register_,
        @SuppressWarnings("hiding") TIdentifier _bit_)
    {
        // Constructor
        setRegister(_register_);

        setBit(_bit_);

    }

    @Override
    public Object clone()
    {
        return new AIndexExpr(
            cloneNode(this._register_),
            cloneNode(this._bit_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIndexExpr(this);
    }

    public TIdentifier getRegister()
    {
        return this._register_;
    }

    public void setRegister(TIdentifier node)
    {
        if(this._register_ != null)
        {
            this._register_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._register_ = node;
    }

    public TIdentifier getBit()
    {
        return this._bit_;
    }

    public void setBit(TIdentifier node)
    {
        if(this._bit_ != null)
        {
            this._bit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._register_)
            + toString(this._bit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._register_ == child)
        {
            this._register_ = null;
            return;
        }

        if(this._bit_ == child)
        {
            this._bit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._register_ == oldChild)
        {
            setRegister((TIdentifier) newChild);
            return;
        }

        if(this._bit_ == oldChild)
        {
            setBit((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
