/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.node;

import be.lmenten.avr.assembler.parser.analysis.*;

@SuppressWarnings("nls")
public final class AInInstruction extends PInstruction
{
    private TRegister _dest_;
    private PExpr _a_;

    public AInInstruction()
    {
        // Constructor
    }

    public AInInstruction(
        @SuppressWarnings("hiding") TRegister _dest_,
        @SuppressWarnings("hiding") PExpr _a_)
    {
        // Constructor
        setDest(_dest_);

        setA(_a_);

    }

    @Override
    public Object clone()
    {
        return new AInInstruction(
            cloneNode(this._dest_),
            cloneNode(this._a_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInInstruction(this);
    }

    public TRegister getDest()
    {
        return this._dest_;
    }

    public void setDest(TRegister node)
    {
        if(this._dest_ != null)
        {
            this._dest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dest_ = node;
    }

    public PExpr getA()
    {
        return this._a_;
    }

    public void setA(PExpr node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dest_)
            + toString(this._a_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dest_ == child)
        {
            this._dest_ = null;
            return;
        }

        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dest_ == oldChild)
        {
            setDest((TRegister) newChild);
            return;
        }

        if(this._a_ == oldChild)
        {
            setA((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
