/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.node;

import be.lmenten.avr.assembler.parser.analysis.*;

@SuppressWarnings("nls")
public final class AMovwInstruction extends PInstruction
{
    private TRegisterPair _dest_;
    private TRegisterPair _src_;

    public AMovwInstruction()
    {
        // Constructor
    }

    public AMovwInstruction(
        @SuppressWarnings("hiding") TRegisterPair _dest_,
        @SuppressWarnings("hiding") TRegisterPair _src_)
    {
        // Constructor
        setDest(_dest_);

        setSrc(_src_);

    }

    @Override
    public Object clone()
    {
        return new AMovwInstruction(
            cloneNode(this._dest_),
            cloneNode(this._src_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMovwInstruction(this);
    }

    public TRegisterPair getDest()
    {
        return this._dest_;
    }

    public void setDest(TRegisterPair node)
    {
        if(this._dest_ != null)
        {
            this._dest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dest_ = node;
    }

    public TRegisterPair getSrc()
    {
        return this._src_;
    }

    public void setSrc(TRegisterPair node)
    {
        if(this._src_ != null)
        {
            this._src_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._src_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dest_)
            + toString(this._src_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dest_ == child)
        {
            this._dest_ = null;
            return;
        }

        if(this._src_ == child)
        {
            this._src_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dest_ == oldChild)
        {
            setDest((TRegisterPair) newChild);
            return;
        }

        if(this._src_ == oldChild)
        {
            setSrc((TRegisterPair) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
