/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.node;

import be.lmenten.avr.assembler.parser.analysis.*;

@SuppressWarnings("nls")
public final class APrologLine extends PLine
{
    private TProlog _keyword_;

    public APrologLine()
    {
        // Constructor
    }

    public APrologLine(
        @SuppressWarnings("hiding") TProlog _keyword_)
    {
        // Constructor
        setKeyword(_keyword_);

    }

    @Override
    public Object clone()
    {
        return new APrologLine(
            cloneNode(this._keyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrologLine(this);
    }

    public TProlog getKeyword()
    {
        return this._keyword_;
    }

    public void setKeyword(TProlog node)
    {
        if(this._keyword_ != null)
        {
            this._keyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keyword_ == child)
        {
            this._keyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keyword_ == oldChild)
        {
            setKeyword((TProlog) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
