/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.node;

import be.lmenten.avr.assembler.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASbisInstruction extends PInstruction
{
    private PExpr _a_;
    private PExpr _b_;

    public ASbisInstruction()
    {
        // Constructor
    }

    public ASbisInstruction(
        @SuppressWarnings("hiding") PExpr _a_,
        @SuppressWarnings("hiding") PExpr _b_)
    {
        // Constructor
        setA(_a_);

        setB(_b_);

    }

    @Override
    public Object clone()
    {
        return new ASbisInstruction(
            cloneNode(this._a_),
            cloneNode(this._b_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASbisInstruction(this);
    }

    public PExpr getA()
    {
        return this._a_;
    }

    public void setA(PExpr node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    public PExpr getB()
    {
        return this._b_;
    }

    public void setB(PExpr node)
    {
        if(this._b_ != null)
        {
            this._b_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._a_)
            + toString(this._b_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        if(this._b_ == child)
        {
            this._b_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._a_ == oldChild)
        {
            setA((PExpr) newChild);
            return;
        }

        if(this._b_ == oldChild)
        {
            setB((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
