/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.node;

import be.lmenten.avr.assembler.parser.analysis.*;

@SuppressWarnings("nls")
public final class AXchInstruction extends PInstruction
{
    private TRegister _src_;

    public AXchInstruction()
    {
        // Constructor
    }

    public AXchInstruction(
        @SuppressWarnings("hiding") TRegister _src_)
    {
        // Constructor
        setSrc(_src_);

    }

    @Override
    public Object clone()
    {
        return new AXchInstruction(
            cloneNode(this._src_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXchInstruction(this);
    }

    public TRegister getSrc()
    {
        return this._src_;
    }

    public void setSrc(TRegister node)
    {
        if(this._src_ != null)
        {
            this._src_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._src_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._src_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._src_ == child)
        {
            this._src_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._src_ == oldChild)
        {
            setSrc((TRegister) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
