/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.analysis;

import java.util.*;

import be.lmenten.avr.assembler.parser.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEmptyLine(AEmptyLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALabelLine(ALabelLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACodeLine(ACodeLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADbLine(ADbLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADwLine(ADwLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADdLine(ADdLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADqLine(ADqLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAReserveLine(AReserveLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASetLine(ASetLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUnsetLine(AUnsetLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEquLine(AEquLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrgLine(AOrgLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACsegLine(ACsegLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADsegLine(ADsegLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEsegLine(AEsegLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrologLine(APrologLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEndprologLine(AEndprologLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAdcInstruction(AAdcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAddInstruction(AAddInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAdiwInstruction(AAdiwInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndInstruction(AAndInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndiInstruction(AAndiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAsrInstruction(AAsrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABclrInstruction(ABclrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABldInstruction(ABldInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrbcInstruction(ABrbcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrbsInstruction(ABrbsInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABreakInstruction(ABreakInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABreqInstruction(ABreqInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrgeInstruction(ABrgeInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrhcInstruction(ABrhcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrhsInstruction(ABrhsInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABridInstruction(ABridInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrieInstruction(ABrieInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrloInstruction(ABrloInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrltInstruction(ABrltInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrmiInstruction(ABrmiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrneInstruction(ABrneInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrplInstruction(ABrplInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrshInstruction(ABrshInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrtcInstruction(ABrtcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrtsInstruction(ABrtsInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrvcInstruction(ABrvcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABrvsInstruction(ABrvsInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABsetInstruction(ABsetInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABstInstruction(ABstInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACallInstruction(ACallInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACbiInstruction(ACbiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACbrInstruction(ACbrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClcInstruction(AClcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClhInstruction(AClhInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACliInstruction(ACliInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClnInstruction(AClnInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClrInstruction(AClrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClsInstruction(AClsInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACltInstruction(ACltInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClvInstruction(AClvInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClzInstruction(AClzInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComInstruction(AComInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACpInstruction(ACpInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACpcInstruction(ACpcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACpiInstruction(ACpiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACpseInstruction(ACpseInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecInstruction(ADecInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADesInstruction(ADesInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEicallInstruction(AEicallInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEijmpInstruction(AEijmpInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEorInstruction(AEorInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFmulInstruction(AFmulInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFmulsInstruction(AFmulsInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFmulsuInstruction(AFmulsuInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIcallInstruction(AIcallInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIjmpInstruction(AIjmpInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInInstruction(AInInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIncInstruction(AIncInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAJmpInstruction(AJmpInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALacInstruction(ALacInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALasInstruction(ALasInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALatInstruction(ALatInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALdiInstruction(ALdiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALslInstruction(ALslInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALsrInstruction(ALsrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMovInstruction(AMovInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMovwInstruction(AMovwInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMulInstruction(AMulInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMulsInstruction(AMulsInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMulsuInstruction(AMulsuInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegInstruction(ANegInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANopInstruction(ANopInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrInstruction(AOrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOriInstruction(AOriInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOutInstruction(AOutInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPopInstruction(APopInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPushInstruction(APushInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARcallInstruction(ARcallInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARetInstruction(ARetInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARetiInstruction(ARetiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARjmpInstruction(ARjmpInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARolInstruction(ARolInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARorInstruction(ARorInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbcInstruction(ASbcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbciInstruction(ASbciInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbiInstruction(ASbiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbicInstruction(ASbicInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbisInstruction(ASbisInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbiwInstruction(ASbiwInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbrInstruction(ASbrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbrcInstruction(ASbrcInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASbrsInstruction(ASbrsInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASecInstruction(ASecInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASehInstruction(ASehInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeiInstruction(ASeiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASenInstruction(ASenInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASerInstruction(ASerInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASesInstruction(ASesInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASetInstruction(ASetInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASevInstruction(ASevInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASezInstruction(ASezInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASleepInstruction(ASleepInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubInstruction(ASubInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubiInstruction(ASubiInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASwapInstruction(ASwapInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATstInstruction(ATstInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAWdrInstruction(AWdrInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAXchInstruction(AXchInstruction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAddExpr(AAddExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubExpr(ASubExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMulExpr(AMulExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivExpr(ADivExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModExpr(AModExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANotExpr(ANotExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndExpr(AAndExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrExpr(AOrExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAXorExpr(AXorExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALshiftExpr(ALshiftExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARshiftExpr(ARshiftExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntegerExpr(AIntegerExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecimalExpr(ADecimalExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstantExpr(AConstantExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAHereExpr(AHereExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAddressExpr(AAddressExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIoaddressExpr(AIoaddressExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIndexExpr(AIndexExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaskExpr(AMaskExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOffsetExpr(AOffsetExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALowExpr(ALowExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAHighExpr(AHighExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPageExpr(APageExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAByte3Expr(AByte3Expr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAByte4Expr(AByte4Expr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALwrdExpr(ALwrdExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAHwrdExpr(AHwrdExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAQ7Expr(AQ7Expr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAQ15Expr(AQ15Expr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntExpr(AIntExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFracExpr(AFracExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAbsExpr(AAbsExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp2Expr(AExp2Expr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALog2Expr(ALog2Expr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegister(TRegister node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegisterPair(TRegisterPair node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegX(TRegX node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegXPostinc(TRegXPostinc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegXPredec(TRegXPredec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegY(TRegY node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegYPostinc(TRegYPostinc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegYPredec(TRegYPredec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegZ(TRegZ node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegZPostinc(TRegZPostinc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRegZPredec(TRegZPredec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMAdc(TMAdc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMAdd(TMAdd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMAdiw(TMAdiw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMAnd(TMAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMAndi(TMAndi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMAsr(TMAsr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBclr(TMBclr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBld(TMBld node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrbc(TMBrbc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrbs(TMBrbs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBreak(TMBreak node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBreq(TMBreq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrge(TMBrge node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrhc(TMBrhc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrhs(TMBrhs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrid(TMBrid node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrie(TMBrie node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrlo(TMBrlo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrlt(TMBrlt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrmi(TMBrmi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrne(TMBrne node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrpl(TMBrpl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrsh(TMBrsh node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrtc(TMBrtc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrts(TMBrts node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrvc(TMBrvc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBrvs(TMBrvs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBset(TMBset node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMBst(TMBst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCall(TMCall node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCbi(TMCbi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCbr(TMCbr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMClc(TMClc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMClh(TMClh node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCli(TMCli node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCln(TMCln node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMClr(TMClr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCls(TMCls node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMClt(TMClt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMClv(TMClv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMClz(TMClz node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCom(TMCom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCp(TMCp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCpc(TMCpc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCpi(TMCpi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMCpse(TMCpse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMDec(TMDec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMDes(TMDes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMEicall(TMEicall node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMEijmp(TMEijmp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMElpm(TMElpm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMEor(TMEor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMFmul(TMFmul node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMFmuls(TMFmuls node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMFmulsu(TMFmulsu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMIcall(TMIcall node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMIjmp(TMIjmp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMIn(TMIn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMInc(TMInc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMJmp(TMJmp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLac(TMLac node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLas(TMLas node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLat(TMLat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLd(TMLd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLdd(TMLdd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLdi(TMLdi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLds(TMLds node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLpm(TMLpm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLsl(TMLsl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMLsr(TMLsr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMMov(TMMov node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMMovw(TMMovw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMMul(TMMul node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMMuls(TMMuls node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMMulsu(TMMulsu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMNeg(TMNeg node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMNop(TMNop node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMOr(TMOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMOri(TMOri node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMOut(TMOut node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMPop(TMPop node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMPush(TMPush node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMRcall(TMRcall node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMRet(TMRet node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMReti(TMReti node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMRjmp(TMRjmp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMRol(TMRol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMRor(TMRor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbc(TMSbc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbci(TMSbci node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbi(TMSbi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbic(TMSbic node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbis(TMSbis node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbiw(TMSbiw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbr(TMSbr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbrc(TMSbrc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSbrs(TMSbrs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSec(TMSec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSeh(TMSeh node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSei(TMSei node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSen(TMSen node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSer(TMSer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSes(TMSes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSet(TMSet node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSev(TMSev node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSez(TMSez node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSleep(TMSleep node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSpm(TMSpm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSt(TMSt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMStd(TMStd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSts(TMSts node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSub(TMSub node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSubi(TMSubi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMSwap(TMSwap node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMTst(TMTst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMWdr(TMWdr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMXch(TMXch node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTProlog(TProlog node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEndprolog(TEndprolog node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOrg(TOrg node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCseg(TCseg node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCsegsize(TCsegsize node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDseg(TDseg node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEseg(TEseg node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOverlap(TOverlap node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNooverlap(TNooverlap node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEqu(TEqu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSet(TSet node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUnset(TUnset node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDef(TDef node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUndef(TUndef node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIf(TIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIfdef(TIfdef node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIfnef(TIfnef node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTElif(TElif node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTElse(TElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEndif(TEndif node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMacro(TMacro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEndm(TEndm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEndmacro(TEndmacro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInclude(TInclude node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTList(TList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTListmac(TListmac node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNolist(TNolist node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTError(TError node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWarning(TWarning node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMessage(TMessage node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExit(TExit node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTByte(TByte node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDb(TDb node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDw(TDw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDd(TDd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDq(TDq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAddress(TAddress node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIoaddress(TIoaddress node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIndex(TIndex node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMask(TMask node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOffset(TOffset node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRelative(TRelative node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTo(TTo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLow(TLow node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTHigh(THigh node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPage(TPage node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLwrd(TLwrd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTHwrd(THwrd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTByte2(TByte2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTByte3(TByte3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTByte4(TByte4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTQ7(TQ7 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTQ15(TQ15 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInt(TInt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFrac(TFrac node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAbs(TAbs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExp2(TExp2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLog2(TLog2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdentifier(TIdentifier node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLabel(TLabel node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTHere(THere node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInteger(TInteger node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDecimal(TDecimal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAdd(TAdd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSub(TSub node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMul(TMul node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMod(TMod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNot(TNot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnd(TAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOr(TOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTXor(TXor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLshift(TLshift node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRshift(TRshift node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNegate(TNegate node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEqual(TEqual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNotEqual(TNotEqual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLower(TLower node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLowerEqual(TLowerEqual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGreater(TGreater node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGreaterEqual(TGreaterEqual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAssign(TAssign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBra(TLBra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBra(TRBra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDot(TDot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColon(TColon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComma(TComma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEol(TEol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlanks(TBlanks node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComment(TComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
