/* This file was generated by SableCC (http://www.sablecc.org/). */

package be.lmenten.avr.assembler.parser.parser;

import be.lmenten.avr.assembler.parser.analysis.*;
import be.lmenten.avr.assembler.parser.node.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTRegister(@SuppressWarnings("unused") TRegister node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRegisterPair(@SuppressWarnings("unused") TRegisterPair node)
    {
        this.index = 1;
    }

    @Override
    public void caseTRegX(@SuppressWarnings("unused") TRegX node)
    {
        this.index = 2;
    }

    @Override
    public void caseTRegXPostinc(@SuppressWarnings("unused") TRegXPostinc node)
    {
        this.index = 3;
    }

    @Override
    public void caseTRegXPredec(@SuppressWarnings("unused") TRegXPredec node)
    {
        this.index = 4;
    }

    @Override
    public void caseTRegY(@SuppressWarnings("unused") TRegY node)
    {
        this.index = 5;
    }

    @Override
    public void caseTRegYPostinc(@SuppressWarnings("unused") TRegYPostinc node)
    {
        this.index = 6;
    }

    @Override
    public void caseTRegYPredec(@SuppressWarnings("unused") TRegYPredec node)
    {
        this.index = 7;
    }

    @Override
    public void caseTRegZ(@SuppressWarnings("unused") TRegZ node)
    {
        this.index = 8;
    }

    @Override
    public void caseTRegZPostinc(@SuppressWarnings("unused") TRegZPostinc node)
    {
        this.index = 9;
    }

    @Override
    public void caseTRegZPredec(@SuppressWarnings("unused") TRegZPredec node)
    {
        this.index = 10;
    }

    @Override
    public void caseTMAdc(@SuppressWarnings("unused") TMAdc node)
    {
        this.index = 11;
    }

    @Override
    public void caseTMAdd(@SuppressWarnings("unused") TMAdd node)
    {
        this.index = 12;
    }

    @Override
    public void caseTMAdiw(@SuppressWarnings("unused") TMAdiw node)
    {
        this.index = 13;
    }

    @Override
    public void caseTMAnd(@SuppressWarnings("unused") TMAnd node)
    {
        this.index = 14;
    }

    @Override
    public void caseTMAndi(@SuppressWarnings("unused") TMAndi node)
    {
        this.index = 15;
    }

    @Override
    public void caseTMAsr(@SuppressWarnings("unused") TMAsr node)
    {
        this.index = 16;
    }

    @Override
    public void caseTMBclr(@SuppressWarnings("unused") TMBclr node)
    {
        this.index = 17;
    }

    @Override
    public void caseTMBld(@SuppressWarnings("unused") TMBld node)
    {
        this.index = 18;
    }

    @Override
    public void caseTMBrbc(@SuppressWarnings("unused") TMBrbc node)
    {
        this.index = 19;
    }

    @Override
    public void caseTMBrbs(@SuppressWarnings("unused") TMBrbs node)
    {
        this.index = 20;
    }

    @Override
    public void caseTMBreak(@SuppressWarnings("unused") TMBreak node)
    {
        this.index = 21;
    }

    @Override
    public void caseTMBreq(@SuppressWarnings("unused") TMBreq node)
    {
        this.index = 22;
    }

    @Override
    public void caseTMBrge(@SuppressWarnings("unused") TMBrge node)
    {
        this.index = 23;
    }

    @Override
    public void caseTMBrhc(@SuppressWarnings("unused") TMBrhc node)
    {
        this.index = 24;
    }

    @Override
    public void caseTMBrhs(@SuppressWarnings("unused") TMBrhs node)
    {
        this.index = 25;
    }

    @Override
    public void caseTMBrid(@SuppressWarnings("unused") TMBrid node)
    {
        this.index = 26;
    }

    @Override
    public void caseTMBrie(@SuppressWarnings("unused") TMBrie node)
    {
        this.index = 27;
    }

    @Override
    public void caseTMBrlo(@SuppressWarnings("unused") TMBrlo node)
    {
        this.index = 28;
    }

    @Override
    public void caseTMBrlt(@SuppressWarnings("unused") TMBrlt node)
    {
        this.index = 29;
    }

    @Override
    public void caseTMBrmi(@SuppressWarnings("unused") TMBrmi node)
    {
        this.index = 30;
    }

    @Override
    public void caseTMBrne(@SuppressWarnings("unused") TMBrne node)
    {
        this.index = 31;
    }

    @Override
    public void caseTMBrpl(@SuppressWarnings("unused") TMBrpl node)
    {
        this.index = 32;
    }

    @Override
    public void caseTMBrsh(@SuppressWarnings("unused") TMBrsh node)
    {
        this.index = 33;
    }

    @Override
    public void caseTMBrtc(@SuppressWarnings("unused") TMBrtc node)
    {
        this.index = 34;
    }

    @Override
    public void caseTMBrts(@SuppressWarnings("unused") TMBrts node)
    {
        this.index = 35;
    }

    @Override
    public void caseTMBrvc(@SuppressWarnings("unused") TMBrvc node)
    {
        this.index = 36;
    }

    @Override
    public void caseTMBrvs(@SuppressWarnings("unused") TMBrvs node)
    {
        this.index = 37;
    }

    @Override
    public void caseTMBset(@SuppressWarnings("unused") TMBset node)
    {
        this.index = 38;
    }

    @Override
    public void caseTMBst(@SuppressWarnings("unused") TMBst node)
    {
        this.index = 39;
    }

    @Override
    public void caseTMCall(@SuppressWarnings("unused") TMCall node)
    {
        this.index = 40;
    }

    @Override
    public void caseTMCbi(@SuppressWarnings("unused") TMCbi node)
    {
        this.index = 41;
    }

    @Override
    public void caseTMCbr(@SuppressWarnings("unused") TMCbr node)
    {
        this.index = 42;
    }

    @Override
    public void caseTMClc(@SuppressWarnings("unused") TMClc node)
    {
        this.index = 43;
    }

    @Override
    public void caseTMClh(@SuppressWarnings("unused") TMClh node)
    {
        this.index = 44;
    }

    @Override
    public void caseTMCli(@SuppressWarnings("unused") TMCli node)
    {
        this.index = 45;
    }

    @Override
    public void caseTMCln(@SuppressWarnings("unused") TMCln node)
    {
        this.index = 46;
    }

    @Override
    public void caseTMClr(@SuppressWarnings("unused") TMClr node)
    {
        this.index = 47;
    }

    @Override
    public void caseTMCls(@SuppressWarnings("unused") TMCls node)
    {
        this.index = 48;
    }

    @Override
    public void caseTMClt(@SuppressWarnings("unused") TMClt node)
    {
        this.index = 49;
    }

    @Override
    public void caseTMClv(@SuppressWarnings("unused") TMClv node)
    {
        this.index = 50;
    }

    @Override
    public void caseTMClz(@SuppressWarnings("unused") TMClz node)
    {
        this.index = 51;
    }

    @Override
    public void caseTMCom(@SuppressWarnings("unused") TMCom node)
    {
        this.index = 52;
    }

    @Override
    public void caseTMCp(@SuppressWarnings("unused") TMCp node)
    {
        this.index = 53;
    }

    @Override
    public void caseTMCpc(@SuppressWarnings("unused") TMCpc node)
    {
        this.index = 54;
    }

    @Override
    public void caseTMCpi(@SuppressWarnings("unused") TMCpi node)
    {
        this.index = 55;
    }

    @Override
    public void caseTMCpse(@SuppressWarnings("unused") TMCpse node)
    {
        this.index = 56;
    }

    @Override
    public void caseTMDec(@SuppressWarnings("unused") TMDec node)
    {
        this.index = 57;
    }

    @Override
    public void caseTMDes(@SuppressWarnings("unused") TMDes node)
    {
        this.index = 58;
    }

    @Override
    public void caseTMEicall(@SuppressWarnings("unused") TMEicall node)
    {
        this.index = 59;
    }

    @Override
    public void caseTMEijmp(@SuppressWarnings("unused") TMEijmp node)
    {
        this.index = 60;
    }

    @Override
    public void caseTMElpm(@SuppressWarnings("unused") TMElpm node)
    {
        this.index = 61;
    }

    @Override
    public void caseTMEor(@SuppressWarnings("unused") TMEor node)
    {
        this.index = 62;
    }

    @Override
    public void caseTMFmul(@SuppressWarnings("unused") TMFmul node)
    {
        this.index = 63;
    }

    @Override
    public void caseTMFmuls(@SuppressWarnings("unused") TMFmuls node)
    {
        this.index = 64;
    }

    @Override
    public void caseTMFmulsu(@SuppressWarnings("unused") TMFmulsu node)
    {
        this.index = 65;
    }

    @Override
    public void caseTMIcall(@SuppressWarnings("unused") TMIcall node)
    {
        this.index = 66;
    }

    @Override
    public void caseTMIjmp(@SuppressWarnings("unused") TMIjmp node)
    {
        this.index = 67;
    }

    @Override
    public void caseTMIn(@SuppressWarnings("unused") TMIn node)
    {
        this.index = 68;
    }

    @Override
    public void caseTMInc(@SuppressWarnings("unused") TMInc node)
    {
        this.index = 69;
    }

    @Override
    public void caseTMJmp(@SuppressWarnings("unused") TMJmp node)
    {
        this.index = 70;
    }

    @Override
    public void caseTMLac(@SuppressWarnings("unused") TMLac node)
    {
        this.index = 71;
    }

    @Override
    public void caseTMLas(@SuppressWarnings("unused") TMLas node)
    {
        this.index = 72;
    }

    @Override
    public void caseTMLat(@SuppressWarnings("unused") TMLat node)
    {
        this.index = 73;
    }

    @Override
    public void caseTMLd(@SuppressWarnings("unused") TMLd node)
    {
        this.index = 74;
    }

    @Override
    public void caseTMLdd(@SuppressWarnings("unused") TMLdd node)
    {
        this.index = 75;
    }

    @Override
    public void caseTMLdi(@SuppressWarnings("unused") TMLdi node)
    {
        this.index = 76;
    }

    @Override
    public void caseTMLds(@SuppressWarnings("unused") TMLds node)
    {
        this.index = 77;
    }

    @Override
    public void caseTMLpm(@SuppressWarnings("unused") TMLpm node)
    {
        this.index = 78;
    }

    @Override
    public void caseTMLsl(@SuppressWarnings("unused") TMLsl node)
    {
        this.index = 79;
    }

    @Override
    public void caseTMLsr(@SuppressWarnings("unused") TMLsr node)
    {
        this.index = 80;
    }

    @Override
    public void caseTMMov(@SuppressWarnings("unused") TMMov node)
    {
        this.index = 81;
    }

    @Override
    public void caseTMMovw(@SuppressWarnings("unused") TMMovw node)
    {
        this.index = 82;
    }

    @Override
    public void caseTMMul(@SuppressWarnings("unused") TMMul node)
    {
        this.index = 83;
    }

    @Override
    public void caseTMMuls(@SuppressWarnings("unused") TMMuls node)
    {
        this.index = 84;
    }

    @Override
    public void caseTMMulsu(@SuppressWarnings("unused") TMMulsu node)
    {
        this.index = 85;
    }

    @Override
    public void caseTMNeg(@SuppressWarnings("unused") TMNeg node)
    {
        this.index = 86;
    }

    @Override
    public void caseTMNop(@SuppressWarnings("unused") TMNop node)
    {
        this.index = 87;
    }

    @Override
    public void caseTMOr(@SuppressWarnings("unused") TMOr node)
    {
        this.index = 88;
    }

    @Override
    public void caseTMOri(@SuppressWarnings("unused") TMOri node)
    {
        this.index = 89;
    }

    @Override
    public void caseTMOut(@SuppressWarnings("unused") TMOut node)
    {
        this.index = 90;
    }

    @Override
    public void caseTMPop(@SuppressWarnings("unused") TMPop node)
    {
        this.index = 91;
    }

    @Override
    public void caseTMPush(@SuppressWarnings("unused") TMPush node)
    {
        this.index = 92;
    }

    @Override
    public void caseTMRcall(@SuppressWarnings("unused") TMRcall node)
    {
        this.index = 93;
    }

    @Override
    public void caseTMRet(@SuppressWarnings("unused") TMRet node)
    {
        this.index = 94;
    }

    @Override
    public void caseTMReti(@SuppressWarnings("unused") TMReti node)
    {
        this.index = 95;
    }

    @Override
    public void caseTMRjmp(@SuppressWarnings("unused") TMRjmp node)
    {
        this.index = 96;
    }

    @Override
    public void caseTMRol(@SuppressWarnings("unused") TMRol node)
    {
        this.index = 97;
    }

    @Override
    public void caseTMRor(@SuppressWarnings("unused") TMRor node)
    {
        this.index = 98;
    }

    @Override
    public void caseTMSbc(@SuppressWarnings("unused") TMSbc node)
    {
        this.index = 99;
    }

    @Override
    public void caseTMSbci(@SuppressWarnings("unused") TMSbci node)
    {
        this.index = 100;
    }

    @Override
    public void caseTMSbi(@SuppressWarnings("unused") TMSbi node)
    {
        this.index = 101;
    }

    @Override
    public void caseTMSbic(@SuppressWarnings("unused") TMSbic node)
    {
        this.index = 102;
    }

    @Override
    public void caseTMSbis(@SuppressWarnings("unused") TMSbis node)
    {
        this.index = 103;
    }

    @Override
    public void caseTMSbiw(@SuppressWarnings("unused") TMSbiw node)
    {
        this.index = 104;
    }

    @Override
    public void caseTMSbr(@SuppressWarnings("unused") TMSbr node)
    {
        this.index = 105;
    }

    @Override
    public void caseTMSbrc(@SuppressWarnings("unused") TMSbrc node)
    {
        this.index = 106;
    }

    @Override
    public void caseTMSbrs(@SuppressWarnings("unused") TMSbrs node)
    {
        this.index = 107;
    }

    @Override
    public void caseTMSec(@SuppressWarnings("unused") TMSec node)
    {
        this.index = 108;
    }

    @Override
    public void caseTMSeh(@SuppressWarnings("unused") TMSeh node)
    {
        this.index = 109;
    }

    @Override
    public void caseTMSei(@SuppressWarnings("unused") TMSei node)
    {
        this.index = 110;
    }

    @Override
    public void caseTMSen(@SuppressWarnings("unused") TMSen node)
    {
        this.index = 111;
    }

    @Override
    public void caseTMSer(@SuppressWarnings("unused") TMSer node)
    {
        this.index = 112;
    }

    @Override
    public void caseTMSes(@SuppressWarnings("unused") TMSes node)
    {
        this.index = 113;
    }

    @Override
    public void caseTMSet(@SuppressWarnings("unused") TMSet node)
    {
        this.index = 114;
    }

    @Override
    public void caseTMSev(@SuppressWarnings("unused") TMSev node)
    {
        this.index = 115;
    }

    @Override
    public void caseTMSez(@SuppressWarnings("unused") TMSez node)
    {
        this.index = 116;
    }

    @Override
    public void caseTMSleep(@SuppressWarnings("unused") TMSleep node)
    {
        this.index = 117;
    }

    @Override
    public void caseTMSpm(@SuppressWarnings("unused") TMSpm node)
    {
        this.index = 118;
    }

    @Override
    public void caseTMSt(@SuppressWarnings("unused") TMSt node)
    {
        this.index = 119;
    }

    @Override
    public void caseTMStd(@SuppressWarnings("unused") TMStd node)
    {
        this.index = 120;
    }

    @Override
    public void caseTMSts(@SuppressWarnings("unused") TMSts node)
    {
        this.index = 121;
    }

    @Override
    public void caseTMSub(@SuppressWarnings("unused") TMSub node)
    {
        this.index = 122;
    }

    @Override
    public void caseTMSubi(@SuppressWarnings("unused") TMSubi node)
    {
        this.index = 123;
    }

    @Override
    public void caseTMSwap(@SuppressWarnings("unused") TMSwap node)
    {
        this.index = 124;
    }

    @Override
    public void caseTMTst(@SuppressWarnings("unused") TMTst node)
    {
        this.index = 125;
    }

    @Override
    public void caseTMWdr(@SuppressWarnings("unused") TMWdr node)
    {
        this.index = 126;
    }

    @Override
    public void caseTMXch(@SuppressWarnings("unused") TMXch node)
    {
        this.index = 127;
    }

    @Override
    public void caseTProlog(@SuppressWarnings("unused") TProlog node)
    {
        this.index = 128;
    }

    @Override
    public void caseTEndprolog(@SuppressWarnings("unused") TEndprolog node)
    {
        this.index = 129;
    }

    @Override
    public void caseTOrg(@SuppressWarnings("unused") TOrg node)
    {
        this.index = 130;
    }

    @Override
    public void caseTCseg(@SuppressWarnings("unused") TCseg node)
    {
        this.index = 131;
    }

    @Override
    public void caseTCsegsize(@SuppressWarnings("unused") TCsegsize node)
    {
        this.index = 132;
    }

    @Override
    public void caseTDseg(@SuppressWarnings("unused") TDseg node)
    {
        this.index = 133;
    }

    @Override
    public void caseTEseg(@SuppressWarnings("unused") TEseg node)
    {
        this.index = 134;
    }

    @Override
    public void caseTOverlap(@SuppressWarnings("unused") TOverlap node)
    {
        this.index = 135;
    }

    @Override
    public void caseTNooverlap(@SuppressWarnings("unused") TNooverlap node)
    {
        this.index = 136;
    }

    @Override
    public void caseTEqu(@SuppressWarnings("unused") TEqu node)
    {
        this.index = 137;
    }

    @Override
    public void caseTSet(@SuppressWarnings("unused") TSet node)
    {
        this.index = 138;
    }

    @Override
    public void caseTUnset(@SuppressWarnings("unused") TUnset node)
    {
        this.index = 139;
    }

    @Override
    public void caseTDef(@SuppressWarnings("unused") TDef node)
    {
        this.index = 140;
    }

    @Override
    public void caseTUndef(@SuppressWarnings("unused") TUndef node)
    {
        this.index = 141;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 142;
    }

    @Override
    public void caseTIfdef(@SuppressWarnings("unused") TIfdef node)
    {
        this.index = 143;
    }

    @Override
    public void caseTIfnef(@SuppressWarnings("unused") TIfnef node)
    {
        this.index = 144;
    }

    @Override
    public void caseTElif(@SuppressWarnings("unused") TElif node)
    {
        this.index = 145;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 146;
    }

    @Override
    public void caseTEndif(@SuppressWarnings("unused") TEndif node)
    {
        this.index = 147;
    }

    @Override
    public void caseTMacro(@SuppressWarnings("unused") TMacro node)
    {
        this.index = 148;
    }

    @Override
    public void caseTEndm(@SuppressWarnings("unused") TEndm node)
    {
        this.index = 149;
    }

    @Override
    public void caseTEndmacro(@SuppressWarnings("unused") TEndmacro node)
    {
        this.index = 150;
    }

    @Override
    public void caseTInclude(@SuppressWarnings("unused") TInclude node)
    {
        this.index = 151;
    }

    @Override
    public void caseTList(@SuppressWarnings("unused") TList node)
    {
        this.index = 152;
    }

    @Override
    public void caseTListmac(@SuppressWarnings("unused") TListmac node)
    {
        this.index = 153;
    }

    @Override
    public void caseTNolist(@SuppressWarnings("unused") TNolist node)
    {
        this.index = 154;
    }

    @Override
    public void caseTError(@SuppressWarnings("unused") TError node)
    {
        this.index = 155;
    }

    @Override
    public void caseTWarning(@SuppressWarnings("unused") TWarning node)
    {
        this.index = 156;
    }

    @Override
    public void caseTMessage(@SuppressWarnings("unused") TMessage node)
    {
        this.index = 157;
    }

    @Override
    public void caseTExit(@SuppressWarnings("unused") TExit node)
    {
        this.index = 158;
    }

    @Override
    public void caseTByte(@SuppressWarnings("unused") TByte node)
    {
        this.index = 159;
    }

    @Override
    public void caseTDb(@SuppressWarnings("unused") TDb node)
    {
        this.index = 160;
    }

    @Override
    public void caseTDw(@SuppressWarnings("unused") TDw node)
    {
        this.index = 161;
    }

    @Override
    public void caseTDd(@SuppressWarnings("unused") TDd node)
    {
        this.index = 162;
    }

    @Override
    public void caseTDq(@SuppressWarnings("unused") TDq node)
    {
        this.index = 163;
    }

    @Override
    public void caseTAddress(@SuppressWarnings("unused") TAddress node)
    {
        this.index = 164;
    }

    @Override
    public void caseTIoaddress(@SuppressWarnings("unused") TIoaddress node)
    {
        this.index = 165;
    }

    @Override
    public void caseTIndex(@SuppressWarnings("unused") TIndex node)
    {
        this.index = 166;
    }

    @Override
    public void caseTMask(@SuppressWarnings("unused") TMask node)
    {
        this.index = 167;
    }

    @Override
    public void caseTOffset(@SuppressWarnings("unused") TOffset node)
    {
        this.index = 168;
    }

    @Override
    public void caseTRelative(@SuppressWarnings("unused") TRelative node)
    {
        this.index = 169;
    }

    @Override
    public void caseTTo(@SuppressWarnings("unused") TTo node)
    {
        this.index = 170;
    }

    @Override
    public void caseTLow(@SuppressWarnings("unused") TLow node)
    {
        this.index = 171;
    }

    @Override
    public void caseTHigh(@SuppressWarnings("unused") THigh node)
    {
        this.index = 172;
    }

    @Override
    public void caseTPage(@SuppressWarnings("unused") TPage node)
    {
        this.index = 173;
    }

    @Override
    public void caseTLwrd(@SuppressWarnings("unused") TLwrd node)
    {
        this.index = 174;
    }

    @Override
    public void caseTHwrd(@SuppressWarnings("unused") THwrd node)
    {
        this.index = 175;
    }

    @Override
    public void caseTByte2(@SuppressWarnings("unused") TByte2 node)
    {
        this.index = 176;
    }

    @Override
    public void caseTByte3(@SuppressWarnings("unused") TByte3 node)
    {
        this.index = 177;
    }

    @Override
    public void caseTByte4(@SuppressWarnings("unused") TByte4 node)
    {
        this.index = 178;
    }

    @Override
    public void caseTQ7(@SuppressWarnings("unused") TQ7 node)
    {
        this.index = 179;
    }

    @Override
    public void caseTQ15(@SuppressWarnings("unused") TQ15 node)
    {
        this.index = 180;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 181;
    }

    @Override
    public void caseTFrac(@SuppressWarnings("unused") TFrac node)
    {
        this.index = 182;
    }

    @Override
    public void caseTAbs(@SuppressWarnings("unused") TAbs node)
    {
        this.index = 183;
    }

    @Override
    public void caseTExp2(@SuppressWarnings("unused") TExp2 node)
    {
        this.index = 184;
    }

    @Override
    public void caseTLog2(@SuppressWarnings("unused") TLog2 node)
    {
        this.index = 185;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 186;
    }

    @Override
    public void caseTLabel(@SuppressWarnings("unused") TLabel node)
    {
        this.index = 187;
    }

    @Override
    public void caseTHere(@SuppressWarnings("unused") THere node)
    {
        this.index = 188;
    }

    @Override
    public void caseTInteger(@SuppressWarnings("unused") TInteger node)
    {
        this.index = 189;
    }

    @Override
    public void caseTDecimal(@SuppressWarnings("unused") TDecimal node)
    {
        this.index = 190;
    }

    @Override
    public void caseTAdd(@SuppressWarnings("unused") TAdd node)
    {
        this.index = 191;
    }

    @Override
    public void caseTSub(@SuppressWarnings("unused") TSub node)
    {
        this.index = 192;
    }

    @Override
    public void caseTMul(@SuppressWarnings("unused") TMul node)
    {
        this.index = 193;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 194;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 195;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 196;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 197;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 198;
    }

    @Override
    public void caseTXor(@SuppressWarnings("unused") TXor node)
    {
        this.index = 199;
    }

    @Override
    public void caseTLshift(@SuppressWarnings("unused") TLshift node)
    {
        this.index = 200;
    }

    @Override
    public void caseTRshift(@SuppressWarnings("unused") TRshift node)
    {
        this.index = 201;
    }

    @Override
    public void caseTNegate(@SuppressWarnings("unused") TNegate node)
    {
        this.index = 202;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 203;
    }

    @Override
    public void caseTNotEqual(@SuppressWarnings("unused") TNotEqual node)
    {
        this.index = 204;
    }

    @Override
    public void caseTLower(@SuppressWarnings("unused") TLower node)
    {
        this.index = 205;
    }

    @Override
    public void caseTLowerEqual(@SuppressWarnings("unused") TLowerEqual node)
    {
        this.index = 206;
    }

    @Override
    public void caseTGreater(@SuppressWarnings("unused") TGreater node)
    {
        this.index = 207;
    }

    @Override
    public void caseTGreaterEqual(@SuppressWarnings("unused") TGreaterEqual node)
    {
        this.index = 208;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 209;
    }

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 210;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 211;
    }

    @Override
    public void caseTLBra(@SuppressWarnings("unused") TLBra node)
    {
        this.index = 212;
    }

    @Override
    public void caseTRBra(@SuppressWarnings("unused") TRBra node)
    {
        this.index = 213;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 214;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 215;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 216;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 217;
    }
}
